[package]
name = "witwiki_migrate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.196"
witwiki_common = { "path" = "../witwiki_common"}
witwiki_db = { "path" = "../witwiki_db"}
