name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: sqlite://wit.db?mode=rwc

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: echo "onchange flow should have run :)"
      # - uses: actions/checkout@v3
      # - name: toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: nightly
      #     override: true
      #     components: rustfmt, clippy
      # - name: init-dev-db
      #   run: cargo run -p witwiki_migrate
      # - uses: Swatinem/rust-cache@v1
      # - run: cargo fmt --check
      # - run: cargo check
      # - run: cargo build
