name: onchange

on: [workflow_call, pull_request]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: sqlite://wit.db?mode=rwc

jobs:
  check:
    name: onchange
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: init-dev-db
        run: cargo run -p witwiki_migrate
      - run: cargo fmt --check
      - run: TASK=check ./onchange.sh
      - run: TASK=build ./onchange.sh
